<!DOCTYPE html>

<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />


    <!-- set a TITLE to appear on the tab header-->
    <title>Asynchronous (pt1)</title>

    <link rel="stylesheet" href="CSS/normalize.css" />
    <link rel="stylesheet" href="CSS/main.css" />
    <link rel="stylesheet" href="CSS/MyStyles.css" />

    <style>
        pre {
            font-size: 12px;
        }
    </style>

</head>
<body class="bodyMove">
    <a href="index.html">Home</a>

    <div class="divFlex">
        <div class="divBorder divBSet">
            <h1>Asynchronous Javascript</h1>

            <p>
                <b>Asynchronous</b> - more than one code thread can be run at the same time. <br />
                <b>Synchronous</b> - (default) code runs as one thread and one command has to finish before the next
                one can start. <br /> <br />

                <h3>Constructing a <a href="https://www.w3schools.com/js/js_promise.asp" target="_blank">Promise</a> Object</h3>
                ...you can also take a look at an MDN document on
                <a href="https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises" target="_blank">Graceful Asynchronous Programming</a>. <br />
                ...and another document (Understanding JavaScript Promises) can be found
                <a href="https://www.digitalocean.com/community/tutorials/understanding-javascript-promises" target="_blank">Here</a>.<br /> <br />

                The Promise constructor method takes a function parameter called the executor function
                which runs automatically when the constructor is called. <br />
                The executor function generally starts an asynchronous operation and dictates
                how the promise should be settled. <br /> <br />

                To create a new Promise object, we use the new keyword and the Promise constructor method:, eg... <br /> <br />

                <b>
                    const executorFunction = (resolve, reject) => { }; <br />
                    const myFirstPromise = new Promise(executorFunction);
                </b> <br /><br />


            </p>
        </div>

        <div class="divBSet divBorder">
            <p>
                The executor function has two function parameters, usually referred to as the
                <b>resolve() and reject() functions</b>. <br />
                The resolve() and reject() functions aren’t defined by the programmer. <br />
                When the Promise constructor runs, JavaScript will pass its own resolve() and reject() functions
                into the executor function. <br /> <br />

                <b>resolve</b> <br />
                is a function with one argument. Under the hood, if invoked, resolve() will
                change the promise’s status from pending to fulfilled, and the promise’s
                resolved value will be set to the argument passed into resolve(). <br /> <br />

                <b>reject</b> <br />
                is a function that takes a reason or error as an argument. Under the hood, if invoked,
                reject() will change the promise’s status from pending to rejected, and the promise’s
                rejection reason will be set to the argument passed into reject(). <br /> <br />

                An example of this could be... <br /> <br />

                <b>
                    const executorFunction = (resolve, reject) => { <br />
                    &nbsp;&nbsp;&nbsp;if (someCondition) { <br />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resolve('I resolved!'); <br />
                    &nbsp;&nbsp;&nbsp;} else { <br />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reject('I rejected!');
                    &nbsp;&nbsp;&nbsp;} <br />
                    } <br /> <br />

                    const myFirstPromise = new Promise(executorFunction); <br /> <br />

                </b>
            </p>

        </div>
    </div>

    <a href="#">Top</a> <br />

    <div class="divFlex">
        <div class="divBorder divBSet">

            <p>
                I had to create a small working file as part of my Codecademy course. <br /> <br />
                It is in a file in the /Scripts folder called <b>sunglasses.js</b>, to run it you can
                open <b>windows command prompt</b> then change directory (cd) in to the folder and then type... <br />
                $ <b>node sunglasses.js</b> <br /> <br />

                The code is also listed below for reference... <br /> <br />

                <pre style="font-size:12px;">
const inventory = {
  sunglasses: 1900,
  pants: 1088,
  bags: 1344
};

const myExecutor = (resolve, reject) => {
  if (inventory.sunglasses > 0) {
    resolve("Sunglasses order processed.");
  } else {
    reject("That item is sold out.");
  };
}

const promiseSunglasses = new Promise(myExecutor);

const orderSunglasses = () => {
  return promiseSunglasses;
}

var orderPromise = orderSunglasses();
console.log(orderPromise);


</pre>
                When this is run it should display, in the console.log, the following message... <br />
                <b>Promise { 'Sunglasses order processed.' }</b> <br /> <br />
            </p>

        </div>

    </div>

    <a href="#">Top</a> <br />

    <div class="divFlex">
        <div class="divBSet divBorder">
            <h2>Something different I came across</h2>

            <p>
                The way you read in (<b>.require</b>) and inherit from a different .js file changes
                the way you refer to the methods in that file. <br /> <br />

                For example... <br /> <br />

                Below are the contents of a file called myLibrary.js... <br /> <br />

                <pre>
const inventory = {
  sunglasses: 1900,
  pants: 1088,
  bags: 1344
};

const checkInventory = (order) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      let inStock = order.every(item => 
inventory[item[0]] >= item[1]);
      if (inStock) {
        resolve(`Thank you. Your order was 
successful.`);
      } else {
        reject(`We're sorry. Your order could 
not be completed because some items are sold out.`);
      }
    }, 1000);
  })
};

module.exports = {checkInventory};

</pre>
            </p>

        </div>

        <div class="divBSet divBorder">
            <p>
                <br />
                There are two ways to <b>.require()</b> the myLibrary.js file in to your main .js file
                that you want to call the routines from... <br /> <br />

                First Way <br />
                <b>const {checkInventory} = require('./myLibrary.js'); </b> <br /> <br />

                OR... <br /> <br />

                Second Way <br />
                <b>const checkInventory = require('./library.js'); </b> <br /> <br />

                <em>
                    <b>Note...</b> <br />
                    You use <b>.require()</b> when running thru the command prompt. <br />
                    And you use import/export (import {method1, method2} from './anotherLibrary.js';) when running
                    on an .html file. <br />
                    Here I am ONLY talking about using the <b>.require()</b> option.
                </em> <br /> <br />

                So when using the FIRST way <br />
                <b>const {checkInventory} = require('./myLibrary.js'); </b> <br />
                you would then call <b>checkInventory()</b> by referring to it as a property (which, I think the {} represents), eg... <br />
                <b>checkInventory(order);</b> <br /> <br />

                Whereas using the SECOND way <br />
                <b>const checkInventory = require('./myLibrary.js'); </b> <br />
                you would then call <b>checkInventory()</b> by referring to the variable name used in the .require()
                followed by a dot (.) and the actual method name used on the <b>myLibrary.js</b> file, eg... <br />
                <b>checkInventory.checkInventory(order);</b> <br />
                <em>a little confusing as I called the imported variable the same as the method name in <b>myLibrary.js</b></em> <br /> <br />

                See below for the <b>FIRST</b> and the <b>SECOND</b> examples as a file (myApp.js) <br /> <br />
            </p>
        </div>
    </div>


    <a href="#">Top</a> <br />

    <div class="divFlex">
        <div class="divBSet divBorder">
            <h2>Example of myApp.js using the FIRST way</h2>

            <p>
                <pre>
<b>const {checkInventory} = require('./myLibrary.js'); </b>

const order = [['sunglasses', 1], ['bags', 2]];

const handleSuccess = (resolvedValue) => {
  console.log(resolvedValue);
};
 
const handleFailure = (rejectionReason) => {
  console.log(rejectionReason);
};

<b>checkInventory(order).then(handleSuccess, 
handleFailure); </b>
//will print on the console.log 
//"Thank you. Your order was successful."
</pre>
            </p>
        </div>

        <div class="divBSet divBorder">
            <h2>Example of myApp.js using the SECOND way</h2>

            <p>
                <pre>
<b>const checkInventory = require('./myLibrary.js'); </b>

const order = [['sunglasses', 1], ['bags', 2]];

const handleSuccess = (resolvedValue) => {
  console.log(resolvedValue);
};
 
const handleFailure = (rejectionReason) => {
  console.log(rejectionReason);
};

<b>checkInventory.checkInventory(order).then(handleSuccess, 
    handleFailure); </b>
//will print on the console.log 
//"Thank you. Your order was successful."

</pre>
            </p>
        </div>
    </div>

    <a href="#">Top</a> <br />

    <div class="divFlex">
        <div class="divBSet divBorder">
            <h2>The box above uses <b>.then()</b></h2>

            <b>.then()</b> is used as part of the 'Success and Failure Callback Functions' <br />
            To handle a “successful” promise, or a promise that resolved, we invoke .then() on the promise, passing
            in a success/failure handler callback function. <br /> <br />

            The two functions (<b>handleSuccess & handleFailure</b>)) form part of this routine <br />
            and the <b>.then()</b> routine uses them, so if the <b>checkInventory()</b> passes or fails then
            the correct message would get sent to the console log. <br /> <br />

            You can try this link for a bit more information
            <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises" target="_blank">See Mozilla</a>
            <br /> <br />

            <p>

            </p>
        </div>

        <div class="divBSet divBorder">
            <h2>Using .catch() with Promises</h2>

            <p>
                One way to write cleaner code is to follow a principle called separation of concerns. <br />
                Separation of concerns means organizing code into distinct sections
                each handling a specific task. <br />
                It enables us to quickly navigate our code and know where to look if something isn’t working. <br /> <br />

                To create even more readable code, we can use a different promise function: .catch(). <br />
                The .catch() function takes only one argument, onRejected. In the case of a rejected promise,
                this failure handler will be invoked with the reason for rejection. <br />
                Using .catch() accomplishes the same thing as using a .then() with only a failure handler. <br /> <br />

                An example of using .catch() could be... <br />

                <pre>
checkInventory(order)
    .then(handleSuccess)
    .catch(handleFailure);
</pre>
                <br />
                Because we already created functions <b>handleSuccess & handleFailure</b> to write out
                to the console.log we only need the above. <br />
                But if we did NOT create handleSuccess or handleFailure to do that we would need to create
                anonymous functions in the .then() and .catch() like so... <br />
                <pre>
checkInventory(order).then((mySuccess) => {
    console.log(mySuccess);
  })
  .catch((myFailure) => {
    console.log(myFailure);
  });
</pre>

            </p>
        </div>
    </div>
    <a href="#">Top</a> <br />

    <div class="divFlex">
        <div class="divBorder divBSet">
            <h2>Chaining multiple promises</h2>

            <p>
                You can chain multiple promises by using multiple <b>.then()</b> commands, eg... <br /> <br />

                <pre>
checkInventory(order)
    .then((resolvedValueArray) => {
      return processPayment(resolvedValueArray);
    })
    .then((resolvedValueArray) => {
      return shipOrder(resolvedValueArray);
    })
    .then((successMessage) => {
      console.log(successMessage);
    })
    .catch((errorMessage) => {
      console.log(errorMessage);
    });

</pre>
                <em>
                    <b>checkInventory</b> is the first task, <b>processPayment</b> is the second and
                    <b>shipOrder</b> is the third task. <br />
                    If ANY of them fail then the .catch() will happen and show
                    the failed message (which is the rejected reason from whatever failed).
                </em> <br /> <br />

                <b>Note</b> <br />
                The <b>.then()</b> commands are chained <b>not</b> nested within each other. <br /> <br />

                When chaining <b>.then()</b>'s remember to make them all return a <b>resolved</b> (success)
                message - except for the last one - as each promise (.then()) needs to have the previous success
                passed to it...below is perhaps a better explanation from the course I am following... <br /> <br />

                <em>
                    ...We invoke checkInventory(order) which returns a promise. <br />
                    ...We invoke .then() with a success handler. <br />
                    ...Inside the success handler, we create our second promise, but we forget to return it! <br />
                    ...We invoke a second .then(). It’s supposed to handle the logic for the second promise,
                    but since we didn’t return, this .then() is invoked on a promise with the same settled
                    value as the original promise! <br /> <br />
                </em>

            </p>

        </div>

        <div class="divBSet divBorder">
            <h3>Common errors people make</h3>
            <p>
                Promise composition allows for much more readable code than the nested callback syntax that preceded it. <br />
                However, it can still be easy to make mistakes. <br />
                This is two common mistakes people make with promise composition. <br /> <br />

                1. Code is nested rather than chained. <br />
                2. Forgetting to return a promise. <br /> <br />

                For example, the following code is wrong, but works... <br />

                <pre>
checkInventory(order)
    .then((resolvedValueArray) => {
        processPayment(resolvedValueArray)
            .then((resolvedValueArray) => {
                shipOrder(resolvedValueArray)
                    .then((successMessage) => {
                        console.log(successMessage);
                    });
            });
    });
</pre>

                The code is nested inside itself and each .test() promise runs 'processPayment' or 'shipOrder'
                but does not <b>return</b> anything. <br /> <br />

                It should look like this... <br />
                <pre>
checkInventory(order)
    .then((resolvedValueArray) => {
        return processPayment(resolvedValueArray);
    })
    .then((resolvedValueArray) => {
        return shipOrder(resolvedValueArray);
    })
    .then((successMessage) => {
        console.log(successMessage);
    });
</pre>

                So each promise (.then()) is chained and each process is returned until, at least, the last one. <br /> <br />
            </p>
        </div>
    </div>

    <a href="#">Top</a> <br />

    <div class="divFlex">
        <div class="divBSet divBorder">
            <h3>Promise.all()</h3>

            <p>
                When done correctly, promise composition is a great way to handle situations where asynchronous
                operations depend on each other or execution order matters. <br />
                What if we’re dealing with multiple promises, but we don’t care about the order? <br />
                For example... <br />

                consider a house clean, we need our clothes to dry, our trash bins emptied, and the dishwasher to run. <br />
                We need all of these tasks to complete but not in any particular order. <br />
                Furthermore, since they’re all getting done asynchronously, they should really all be happening at the same time! <br /> <br />

                To maximize efficiency we should use concurrency, multiple asynchronous operations happening together. <br />
                With promises, we can do this with the function <b>Promise.all()</b>. <br />

                <b>Promise.all()</b> accepts an array of promises as its argument and returns a single promise, eg... <br />
                <b>Promise.all([promise1, promise2, promise3, etc...]);</b> <br /> <br />

                If every promise in the argument array resolves, the single promise returned from Promise.all() will resolve
                with an array containing the resolve value from each promise in the argument array. <br /> <br />

                If any promise from the argument array rejects, the single promise returned from Promise.all() will immediately
                reject with the reason that promise rejected. <br /> <br />
            </p>
        </div>

        <div class="divBSet divBorder">
            <p>
                <br />
                As an example of Promise.all() please see below... <br /> <br />

                <b>
                    Promise.all([checkSunglasses, checkPants, checkBags]) <br />
                    &nbsp;&nbsp;&nbsp;.then(onFulfill) <br />
                    &nbsp;&nbsp;&nbsp;.catch(onReject); <br /> <br />
                </b>

                <em>
                    Where <b>checkSunglasses, checkPants and checkBags</b> are all routines that call a promise routine
                    to check stock numbers. <br /> <br />

                    If they ALL run through okay then a <b>resolve</b> message is passed back for each routine. <br />
                    If one of the routines failed then a <b>reject</b> message is passed back from the failed routine.
                </em> <br /> <br />

                See the two panes below for a small working example. <br />
                The file <b>library.js</b> holds the Promise routines and is Exported - then Imported in to <b>app.js</b> which uses them. <br /> <br />


            </p>

        </div>
    </div>

    <a href="#">Top</a> <br />

    <div class="divFlex">
        <div class="divBSet divBorder">
            <h3>library.js</h3>

            <p>
                holds the Promise routines and is Exported... <br /> <br />

                <pre>
const checkAvailability = (itemName, distributorName) => {
    console.log(`Checking availability 
of ${itemName} at ${distributorName}...`);
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            if (restockSuccess()) {
                console.log(`${itemName} are in stock 
at ${distributorName}`)
                resolve(itemName);
            } else {
                reject(`Error: ${itemName} is unavailable 
from ${distributorName} at this time.`);
            }
        }, 1000);
    });
};

module.exports = { checkAvailability };

// This is a function that returns true 80% of the time
// We're using it to simulate a request to the distributor 
// being successful this often
function restockSuccess() {
    return (Math.random() > .2);
}
</pre>

            </p>
        </div>

        <div class="divBSet divBorder">
            <h3>app.js</h3>

            <p>
                imports from library.js and uses its routines... <br /> <br />

                <pre>
const {checkAvailability} = require('./library.js');

const onFulfill = (itemsArray) => {
  console.log(`Items checked: ${itemsArray}`);
  console.log(`Every item was available from the 
distributor. Placing order now.`);
};

const onReject = (rejectionReason) => {
	console.log(rejectionReason);
};

// Write your code below:
const checkSunglasses = checkAvailability(
"sunglasses", "Favorite Supply Co.");

const checkPants = checkAvailability(
"pants", "Favorite Supply Co.");

const checkBags = checkAvailability("
bags", "Favorite Supply Co.");

let myPromises = Promise.all([checkSunglasses, 
checkPants, checkBags]);
// NOTE
// If you need to use the 'await' command
// (explained in Asynchronous Javascript (pt2) page)
// you would just say
// let myPromises = await Promise.all(...etc)

myPromises
  .then(onFulfill)
  .catch(onReject);

console.log("Will you do it again");

Promise.all([checkSunglasses, checkPants, checkBags])
  .then(onFulfill)
  .catch(onReject);

</pre>
            </p>

        </div>
    </div>
    <a href="#">Top</a> <br />

</body>
</html>